version: '3.8'

services:
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  flask_app:
    build: .
    depends_on:
      - redis
    environment:
      API_KEY: ""
      DEVICE: "wlan0"
      PORT: 80
      SERVER_ID: 38461
      DEBUG: "false"
      SCAN_CRON: 30
      SERVERID: "false"
    ports:
      - "80:80"
    volumes:
      - .:/app
    command: sh -c "redis-server --daemonize yes && celery -A app.celery worker --loglevel=info & gunicorn -w 4 -b 0.0.0.0:80 --timeout 120 app:app"

volumes:
  redis_data:
